# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9d7671695a881978849c5cfe6e5267c5618ba2c4b700a8ae94de77b12650578a882d7ff2d8037c5921f9d73abbe367fa988668c3d3a5a29c2c9d471c65594bd

test:
  secret_key_base: a7b0a75e3742cca5546c873ca652dff62a7413f21efdb472d60fbf3aa405fcdb1af4d8a6acb61f1f7030e0ae1a92961dce3f12f13b08a83d2c7285fa3e3c67f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
